/**
 * Corpus de la revisión adversaria de las reglas de cláusulas adicionales
 * (Entrega 4, 2026-09-21/22): los textos con los que se intentó colar cada
 * categoría (sinónimos, pasiva, título + texto, NFD, letras que no pliegan) y
 * los falsos positivos que aparecieron. Cada fila: [código que debe salir, o
 * '' = ningún hallazgo; texto; título (por defecto «Obligaciones especiales»)].
 *
 * Huecos conocidos, fuera del corpus (las reglas juzgan oración por oración y
 * no leen intención; eso queda para la IA): «…no tiene mascotas. En caso de
 * tenerlas, deberá … obtener autorización» (el pronombre cruza la oración) y
 * «no podrá reclamar … por los daños que él mismo cause a sus propios enseres»
 * (bloquea de más).
 */

const nfd = (s: string) => s.normalize('NFD');

export const CASOS: [codigo: string, texto: string, titulo?: string][] = [
  // ── deposito ──
  ['deposito', 'EL ARRENDATARIO entregará dos meses de depósito al firmar el contrato.'],
  ['deposito', 'Al momento de la firma, EL ARRENDATARIO pagará un mes de depósito.'],
  ['deposito', 'Se exigirá un mes de depósito.'],
  ['deposito', 'EL ARRENDATARIO dará un mes de canon en garantía.'],
  ['deposito', 'EL ARRENDATARIO entregará dos meses de canon como garantía del cumplimiento.'],
  ['deposito', 'EL ARRENDATARIO entregará el equivalente a dos cánones como garantía.'],
  ['deposito', 'EL ARRENDATARIO consignará, a título de depósito, la suma de $1.000.000.'],
  ['deposito', 'El depósito será de $1.500.000, reembolsable al final.'],
  ['deposito', 'EL ARRENDATARIO pagará los dos primeros meses por adelantado.'],
  ['deposito', 'EL ARRENDATARIO otorgará una garantía hipotecaria sobre un inmueble de su propiedad.'],
  ['deposito', 'EL ARRENDATARIO otorgará una garantía real a favor del ARRENDADOR.'],
  ['deposito', 'Se cobrará un depósito de dos meses.'],
  ['deposito', 'Depósito: dos meses de canon.'],
  ['deposito', 'EL ARRENDATARIO deberá dejar dos meses de depósito.'],
  ['deposito', 'El arrendatario pagará dos meses de depósito, los cuales se devolverán al finalizar.'],
  ['deposito', 'Además del canon, EL ARRENDATARIO entregará una suma igual a dos cánones como depósito.'],
  ['deposito', 'EL ARRENDATARIO entregará un depósito de $1.500.000 que se devolverá al finalizar.'],
  ['deposito', 'EL ARRENDATARIO entregará el equivalente a dos cánones, que se le devolverán al finalizar.', 'Depósito'],
  ['deposito', 'EL ARRENDATARIO consignará $2.000.000 al firmar el contrato.', 'Garantía'],
  ['deposito', nfd('EL ARRENDATARIO entregará un depósito en dinero equivalente a dos cánones, que se devolverá al terminar.')],
  ['deposito', nfd('Como garantía consignará la suma de dos millones de pesos.')],
  ['deposito', nfd('EL ARRENDATARIO entregará un depósito de dos cánones en garantía, que se devolverá al final.'), nfd('Garantía')],
  ['deposito', 'EL ARRENDATARIO consignará dos meses como garantía.'],
  ['deposito', 'EL ARRENDATARIO entregará un canon adicional como garantía de cumplimiento.'],
  ['deposito', 'EL ARRENDATARIO hará un depósito de $1.500.000 que se devolverá al finalizar el contrato.'],
  ['deposito', 'Al firmar se hará un depósito de un millón de pesos.'],
  ['deposito', 'EL ARRENDATARIO entregará la suma de $1.500.000 que le será devuelta al terminar el contrato.'],
  ['deposito', 'EL ARRENDATARIO pagará por anticipado los tres primeros cánones.'],
  ['deposito', 'EL ARRENDATARIO entregará $2.000.000 al firmar. Esta suma se devolverá al terminar el contrato.'],
  ['deposito', 'EL ARRENDATARIO dejará un mes de depósito.'],
  ['deposito', 'EL ARRENDATARIO entregará dos (2) meses de arriendo como respaldo.'],
  ['deposito', 'EL ARRENDATARIO entregará un mes de anticipo como garantía.'],
  // ── mascotas ──
  ['mascotas', 'No está permitido tener perros en el inmueble.'],
  ['mascotas', 'No es permitida la tenencia de mascotas.'],
  ['mascotas', 'EL ARRENDATARIO se abstendrá de tener mascotas en el inmueble.'],
  ['mascotas', 'EL ARRENDATARIO no tendrá mascotas en el inmueble.'],
  ['mascotas', 'Las mascotas no podrán permanecer en el inmueble.'],
  ['mascotas', 'Las mascotas deberán ser autorizadas por EL ARRENDADOR.'],
  ['mascotas', 'Para tener mascotas se requiere autorización del ARRENDADOR.'],
  ['mascotas', 'Se permite una sola mascota por apartamento.'],
  ['mascotas', 'La presencia de mascotas facultará al ARRENDADOR para terminar el contrato.'],
  ['mascotas', 'No está permitida la tenencia de mascotas en el inmueble.'],
  ['mascotas', 'No están permitidas las mascotas en el inmueble.'],
  ['mascotas', 'No está permitido el ingreso de mascotas al inmueble.'],
  ['mascotas', 'Está prohibida su tenencia en el inmueble.', 'Mascotas'],
  ['mascotas', 'No se permite su ingreso ni permanencia en el inmueble.', 'Animales de compañía'],
  ['mascotas', 'EL ARRENDATARIO requerirá autorización previa y escrita del ARRENDADOR.', 'Tenencia de mascotas'],
  ['mascotas', 'Solo se admite una por inmueble, previa autorización escrita del ARRENDADOR.', 'Mascotas'],
  ['mascotas', 'EL ARRENDATARIO no podrá tenerlas en el inmueble.', 'Mascotas'],
  ['mascotas', 'Solo se permite una por apartamento.', 'Mascotas'],
  ['mascotas', 'Requieren autorización previa y escrita del ARRENDADOR.', 'Mascotas'],
  ['mascotas', nfd('Se prohíbe tener mascotas en el inmueble.')],
  ['mascotas', 'Por cada perro se cobrará un incremento de $50.000 en el canon.'],
  ['mascotas', 'Si EL ARRENDATARIO tiene mascota, pagará $50.000 mensuales adicionales.'],
  ['mascotas', 'No se admiten perros.'],
  ['mascotas', 'El inmueble se arrienda sin animales.'],
  ['mascotas', 'No se permite ningún tipo de mascota.'],
  ['mascotas', 'Queda prohibida la tenencia de perros y gatos.'],
  // ── incremento ──
  ['incremento', 'El canon se ajustará anualmente en un 8 %.'],
  ['incremento', 'El canon se actualizará cada seis meses.'],
  ['incremento', 'La mensualidad se incrementará en un 10 % cada año.'],
  ['incremento', 'El canon se incrementará en el IPC + 3 puntos.'],
  ['incremento', 'El canon se incrementará anualmente en el IPC sumado a dos puntos.'],
  ['incremento', 'El canon se incrementará anualmente en el doble del IPC.'],
  ['incremento', 'El canon se incrementará anualmente en el ciento cincuenta por ciento del IPC.'],
  ['incremento', 'El canon se reajustará dos veces al año.'],
  ['incremento', 'El canon se ajustará semestralmente.'],
  ['incremento', 'El canon se ajustará anualmente en el IPC más dos puntos.'],
  ['incremento', 'El canon de arrendamiento se ajustará en un 8% anual.'],
  ['incremento', 'La mensualidad se reajustará cada seis meses.'],
  ['incremento', 'El canon se incrementará en el IPC y 3 puntos.'],
  ['incremento', 'El canon de arrendamiento se reajustará anualmente en IPC + 2 puntos.'],
  ['incremento', 'El canon tendrá un ajuste anual del 8 %.'],
  ['incremento', 'El canon se reajustará anualmente en IPC+2.'],
  ['incremento', 'El valor mensual del arriendo tendrá un ajuste semestral.'],
  ['incremento', 'Será del 10 % anual.', 'Reajuste del canon'],
  ['incremento', 'Se hará cada seis meses.', 'Incremento del canon'],
  ['incremento', 'Cada año de ejecución del contrato se incrementará en un porcentaje equivalente al IPC más cinco puntos.', 'Incremento del canon'],
  ['incremento', 'Cada seis meses se reajustará en el IPC.', 'Reajuste del canon'],
  ['incremento', 'Será del IPC más cinco puntos.', 'Incremento del canon'],
  ['incremento', 'EL ARRENDATARIO acepta un aumento del 10 % cada año.', 'Incremento del canon'],
  ['incremento', nfd('El canon se incrementará en el IPC más tres puntos cada año.')],
  ['incremento', 'El valor mensual del arrendamiento se incrementará en el IPC + 3 puntos.'],
  ['incremento', 'El canon se reajustará anualmente en el porcentaje que determine EL ARRENDADOR.'],
  ['incremento', 'El canon se reajustará cada seis meses.'],
  ['incremento', 'El canon se reajustará cada seis (6) meses.'],
  ['incremento', 'El canon se incrementará en el IPC más dos puntos porcentuales.'],
  ['incremento', 'El canon se incrementará cada año en el IPC y dos puntos adicionales.'],
  // ── fianza ──
  ['fianza', 'La cobertura se amplía a 24 cánones.'],
  ['fianza', 'La fianza de Cofianza no cubrirá la administración.'],
  ['fianza', 'EL ARRENDADOR no informará a la entidad garante los incumplimientos del ARRENDATARIO.'],
  ['fianza', 'El valor de la prima del seguro de arrendamiento lo pagará EL ARRENDATARIO.'],
  ['fianza', 'EL ARRENDATARIO asumirá el costo de la póliza de arrendamiento.'],
  ['fianza', 'El amparo de arrendamiento se limita a doce meses.'],
  ['fianza', 'La garantía de arrendamiento no cubrirá las cuotas de administración.'],
  // tarifa, prima y cobertura sin nombrar la fianza (trazabilidad 2026-09-22)
  ['fianza', 'EL ARRENDATARIO no pagará la tarifa mensual.'],
  ['fianza', 'La prima la pagará EL ARRENDADOR.'],
  ['fianza', 'La tarifa será asumida por la inmobiliaria.'],
  ['fianza', 'Las cuotas de administración quedan amparadas.'],
  ['fianza', 'Los servicios públicos que deje de pagar EL ARRENDATARIO estarán cubiertos.'],
  // ── renuncia ──
  ['renuncia', 'EL ARRENDADOR queda exonerado de toda responsabilidad por daños en el inmueble.'],
  ['renuncia', 'EL ARRENDADOR no será responsable por los daños causados por humedades, filtraciones o vicios del inmueble.'],
  ['renuncia', 'EL ARRENDATARIO no tendrá derecho a indemnización alguna.'],
  ['renuncia', 'Si EL ARRENDADOR vende el inmueble, el inquilino renuncia a cualquier indemnización.'],
  ['renuncia', 'EL ARRENDATARIO renuncia a los requerimientos para constituirlo en mora y a cualquier acción judicial contra EL ARRENDADOR.'],
  ['renuncia', 'Las reparaciones necesarias estarán a cargo del ARRENDATARIO.'],
  ['renuncia', 'El arrendador queda exonerado de toda responsabilidad.'],
  ['renuncia', 'EL ARRENDADOR quedará eximido de cualquier responsabilidad por las reparaciones necesarias.'],
  ['renuncia', 'EL PROPIETARIO no responderá por los vicios ocultos del inmueble.'],
  ['renuncia', 'EL ARRENDADOR queda exonerado de cualquier responsabilidad por vicios del inmueble.'],
  ['renuncia', 'EL ARRENDADOR queda eximido de efectuar las reparaciones necesarias.'],
  ['renuncia', 'EL ARRENDATARIO declara que no presentará reclamación alguna contra EL ARRENDADOR.'],
  ['renuncia', 'Frente al ARRENDADOR, el inquilino renuncia a cualquier indemnización.'],
  ['renuncia', 'Todas las reparaciones, incluidas las necesarias, correrán por cuenta de EL ARRENDATARIO.'],
  ['renuncia', 'EL ARRENDATARIO renuncia al preaviso.'],
  ['renuncia', 'EL ARRENDATARIO renuncia expresamente a los derechos de retención.'],
  ['renuncia', 'EL ARRENDATARIO asumirá las reparaciones necesarias del inmueble.'],
  ['renuncia', 'EL ARRENDATARIO pagará las reparaciones necesarias que requiera el inmueble.'],
  ['renuncia', 'Las reparaciones necesarias las hará EL ARRENDATARIO.'],
  // ── terminacion ──
  ['terminacion', 'El incumplimiento de esta obligación constituirá justa causa para dar por terminado el contrato.'],
  ['terminacion', 'La violación de esta norma será motivo de terminación del contrato.'],
  ['terminacion', 'La violación de esta norma será causa justa para terminar el contrato.'],
  ['terminacion', 'El incumplimiento facultará al ARRENDADOR para dar por terminado el contrato.'],
  ['terminacion', 'EL ARRENDADOR tendrá derecho a terminar el contrato si hay visitas nocturnas.'],
  ['terminacion', 'El contrato terminará si EL ARRENDATARIO recibe visitas después de las 10 p.m.'],
  ['terminacion', 'El contrato no será prorrogable.'],
  ['terminacion', 'El contrato no tendrá prórrogas automáticas.'],
  ['terminacion', 'No habrá prórroga del contrato.'],
  ['terminacion', 'El plazo del contrato será de seis meses.'],
  ['terminacion', 'El contrato durará seis meses.'],
  ['terminacion', 'EL ARRENDATARIO que desee entregar el inmueble deberá avisar por escrito con seis (6) meses de anticipación.'],
  ['terminacion', 'El contrato no es prorrogable.'],
  ['terminacion', 'El presente contrato no admite prórroga.'],
  ['terminacion', 'Al vencimiento EL ARRENDATARIO restituirá el inmueble sin que haya lugar a prórroga.'],
  ['terminacion', 'EL ARRENDATARIO dará aviso por escrito con seis (6) meses de antelación a la entrega.'],
  ['terminacion', 'El incumplimiento de esta obligación será justa causa para dar por terminado el contrato.'],
  ['terminacion', 'EL ARRENDADOR podrá dar por terminado el contrato si hay visitas nocturnas.'],
  ['terminacion', 'EL ARRENDADOR podrá terminar el contrato con un aviso de 15 días.'],
  ['terminacion', 'El contrato se dará por terminado de pleno derecho si EL ARRENDATARIO subarrienda.'],
  // ── tenencia ──
  ['tenencia', 'EL ARRENDADOR podrá cambiar la cerradura del inmueble si hay mora.'],
  ['tenencia', 'EL ARRENDADOR podrá cambiar la chapa de la puerta principal en caso de mora.'],
  ['tenencia', 'En caso de mora de dos meses se suspenderán los servicios públicos del inmueble.'],
  ['tenencia', 'En caso de mora, se cambiarán las guardas del inmueble.'],
  ['tenencia', 'En caso de mora superior a dos meses, podrá cambiar las guardas.'],
  ['tenencia', 'EL ARRENDADOR podrá cambiar las guardas sin necesidad de acudir ante un juez.'],
  ['tenencia', 'EL ARRENDADOR podrá retirar los enseres sin acudir a un proceso de restitución.'],
  ['tenencia', 'LA ADMINISTRACIÓN cambiará las guardas si el arrendatario no paga.'],
  ['tenencia', 'EL ARRENDADOR podrá cambiar la llave del inmueble si hay mora.'],
  ['tenencia', 'En caso de mora superior a dos meses, podrá cambiar las guardas.', 'Facultades del arrendador en mora'],
  ['tenencia', 'En caso de mora se cortarán los servicios públicos.'],
  ['tenencia', 'EL ARRENDADOR podrá retirar los enseres sin necesidad de demanda judicial.'],
  ['tenencia', 'EL ARRENDADOR, en caso de mora del ARRENDATARIO, podrá cambiar las guardas.'],
  ['tenencia', 'EL ARRENDATARIO acepta que EL ARRENDADOR cambie las guardas.'],
  ['tenencia', 'EL ARRENDADOR podrá hacerlo si el arrendatario no paga.', 'Cambio de guardas'],
  ['tenencia', 'LA INMOBILIARIA podrá desactivar las tarjetas de acceso del ARRENDATARIO si hay mora.'],
  ['tenencia', 'LA INMOBILIARIA podrá bloquear el acceso al inmueble si hay mora.'],
  ['tenencia', 'EL ARRENDADOR podrá cambiar las guardas sin necesidad de proceso judicial.'],
  ['tenencia', 'EL ARRENDADOR podrá cambiar las guardas sin iniciar el proceso de restitución ante el juez.'],
  // ── modifica_contrato ──
  ['modifica_contrato', 'En caso de contradicción con el contrato, prevalecerá lo aquí pactado.'],
  ['modifica_contrato', 'En caso de contradicción, primará lo dispuesto en esta cláusula.'],
  ['modifica_contrato', 'La cláusula penal no aplicará para este contrato.'],
  ['modifica_contrato', 'Se modifica durante este contrato la cláusula penal.'],
  ['modifica_contrato', nfd('Esta cláusula prevalece sobre las demás cláusulas del contrato.')],
  ['modifica_contrato', 'En caso de contradicción, se aplicará lo dispuesto en esta cláusula adicional.'],
  ['modifica_contrato', 'Las partes acuerdan excluir la cláusula de intereses.'],
  ['modifica_contrato', 'Lo pactado en la cláusula penal no será exigible.'],
  // ── no_imprimible ──
  ['no_imprimible', 'Se pro\u{34f}hibe tener mascotas en el inmueble.'],
  ['no_imprimible', 'Entregará un depo\u{fe0f}sito en dinero equivalente a dos cánones.'],
  ['no_imprimible', 'Se proh\u{131}be tener mascotas en el inmueble.'],
  ['no_imprimible', 'Entregará un depós\u{131}to en dinero equivalente a dos cánones.'],
  ['no_imprimible', 'El canon se \u{131}ncrementará en el IPC más tres puntos cada año.'],
  ['no_imprimible', 'Se pro\u{269}be tener mascotas en el inmueble.'],
  ['no_imprimible', 'La co\u{fb01}anza cubre la administración.'],
  // ── deben pasar ──
  ['', 'El inmueble incluye el depósito No. 12 y el parqueadero No. 45.'],
  ['', 'EL ARRENDATARIO podrá usar el depósito ubicado en el sótano del edificio para guardar sus enseres.'],
  ['', 'EL ARRENDATARIO pagará el canon mediante depósito en la cuenta de ahorros del ARRENDADOR.'],
  ['', 'El depósito asignado al apartamento es el número 7, de uso exclusivo de EL ARRENDATARIO.'],
  ['', 'EL ARRENDATARIO mantendrá el depósito (cuarto útil) limpio y no guardará en él sustancias inflamables.'],
  ['', 'Los electrodomésticos del inmueble tienen seis meses de garantía del fabricante.'],
  ['', 'EL ARRENDATARIO retirará todos sus muebles y enseres al restituir el inmueble al ARRENDADOR.'],
  ['', 'Al finalizar, EL ARRENDATARIO desconectará los servicios de TV e internet contratados a su nombre y entregará paz y salvo al ARRENDADOR.'],
  ['', 'EL ARRENDATARIO podrá cambiar las guardas a su costo, informando al ARRENDADOR.'],
  ['', 'EL ARRENDATARIO podrá tomar posesión del inmueble una vez firme el acta de entrega con EL ARRENDADOR.'],
  ['', 'Si EL ARRENDATARIO cambia las chapas, deberá entregar una copia de las llaves al ARRENDADOR.'],
  ['', 'EL ARRENDATARIO podrá cambiar las cerraduras previa autorización del ARRENDADOR.'],
  ['', 'EL ARRENDATARIO retirará del inmueble los muebles del propietario.'],
  ['', 'EL ARRENDATARIO deberá suspender los servicios de internet y televisión que haya contratado y entregar al ARRENDADOR el paz y salvo.'],
  ['', 'EL ARRENDATARIO asumirá el costo del cambio de chapas dañadas y entregará copia de las llaves al ARRENDADOR.'],
  ['', 'EL ARRENDATARIO pagará el cambio de guardas cuando pierda las llaves que le entregó EL ARRENDADOR.'],
  ['', 'El cambio de guardas lo paga EL ARRENDATARIO, informando al ARRENDADOR.'],
  ['', 'Al restituir el inmueble, EL ARRENDATARIO retirará sus pertenencias y entregará las llaves al ARRENDADOR.'],
  ['', 'EL ARRENDADOR entregará el inmueble con la cerradura en buen estado.'],
  ['', 'EL ARRENDATARIO no permitirá que sus mascotas causen ruidos molestos a los vecinos.'],
  ['', 'EL ARRENDATARIO no permitirá el ingreso de sus mascotas a la piscina del conjunto.'],
  ['', 'Está prohibido dejar excrementos de las mascotas en las zonas comunes.'],
  ['', 'La tenencia de mascotas no está prohibida; EL ARRENDATARIO responderá por los daños.'],
  ['', 'EL ARRENDATARIO podrá tener mascotas y responderá por los daños que causen, sin importar su raza o tamaño.'],
  ['', 'EL ARRENDATARIO mantendrá a su mascota en un espacio adecuado a su tamaño y necesidades.'],
  ['', 'EL ARRENDATARIO cumplirá las normas sobre perros de razas potencialmente peligrosas.'],
  ['', 'El canon se reajustará cada doce meses conforme a la ley, y en caso de mora EL ARRENDATARIO pagará intereses del 2 % mensual.'],
  ['', 'La administración se ajustará según la asamblea.'],
  ['', 'El canon se reajustará cada doce meses hasta el noventa por ciento del IPC.'],
  ['', 'En caso de terminación anticipada, EL ARRENDATARIO entregará las llaves en la oficina de la inmobiliaria.'],
  ['', 'EL ARRENDATARIO tomará un seguro de hogar con vigencia de un (1) año, renovable.'],
  ['', 'A la terminación del contrato, EL ARRENDATARIO indemnizará los daños que haya causado al inmueble.'],
  ['', 'EL ARRENDADOR avisará con dos días de anticipación las visitas al inmueble.'],
  ['', 'EL ARRENDATARIO reparará los daños que cause en el plazo de tres días.'],
  ['', 'Las partes fijarán la cita de entrega con ocho días de antelación.'],
  ['', 'La tenencia de mascotas no facultará al ARRENDADOR para terminar el contrato.'],
  ['', 'EL ARRENDATARIO responderá por los daños que causen y recogerá sus desechos.', 'Mascotas'],
  ['', 'EL ARRENDADOR no será responsable por hurtos de terceros.'],
  ['', 'EL ARRENDATARIO renuncia a los requerimientos privados y judiciales para constituirlo en mora.'],
  ['', 'EL ARRENDADOR renuncia a cobrar intereses de mora durante los primeros cinco días.'],
  ['', 'EL ARRENDATARIO no realizará modificaciones al apartamento durante la vigencia del presente contrato.'],
  ['', 'EL ARRENDATARIO no podrá hacer modificaciones locativas sin autorización del ARRENDADOR durante el contrato.'],
  ['', 'EL ARRENDATARIO no hará modificaciones a los muros ni a la cocina durante este contrato.'],
  ['', 'Cualquier modificación de este contrato deberá hacerse mediante otrosí firmado por las partes.'],
  ['', 'EL ARRENDATARIO reemplazará los bombillos dañados durante el contrato.'],
  ['', 'EL ARRENDATARIO reemplazará los vidrios rotos conforme a lo dispuesto en el reglamento de propiedad horizontal.'],
  ['', 'EL ARRENDATARIO no podrá hacer modificaciones al apartamento durante este contrato.'],
  ['', 'Queda prohibido hacer modificaciones locativas durante el contrato.'],
  ['', 'Toda modificación al presente contrato deberá hacerse mediante otrosí firmado por las partes.'],
  ['', 'Cualquier modificación a este contrato se hará mediante otrosí.'],
  ['', 'EL ARRENDATARIO mantendrá durante el arrendamiento un seguro de hogar con cobertura de incendio.'],
  ['', 'EL ARRENDATARIO tomará un seguro con cobertura de responsabilidad civil durante el arrendamiento.'],
  ['', 'EL ARRENDATARIO podrá contratar un seguro con cobertura sobre sus bienes durante el arriendo.'],
  ['', 'El seguro del inmueble objeto del arrendamiento con cobertura de incendio lo paga EL ARRENDADOR.'],
  ['', nfd('EL ARRENDATARIO pagará la cuota de administración y cuidará el jardín del inmueble.')],
  ['', 'Las mascotas circularán con traílla por las zonas comunes, según el reglamento de propiedad horizontal.'],
  ['', 'EL ARRENDATARIO responderá por los daños que causen sus mascotas y pagará la fumigación al entregar el inmueble.'],
  ['', 'Cada doce (12) meses el canon se reajustará en un porcentaje igual al cien por ciento (100 %) del IPC del año anterior.'],
  ['', 'El canon se pagará dentro de los cinco primeros días de cada mes y se reajustará cada doce meses hasta el 100 % del IPC.'],
  ['', 'La cuota de administración se incrementará según lo que apruebe la asamblea de copropietarios.'],
  ['', 'EL ARRENDATARIO no podrá subir muebles por el ascensor principal; el canon incluye el uso del parqueadero.'],
  ['', 'Si EL ARRENDATARIO paga el canon con tarjeta, asumirá la comisión del 3 % que cobre la pasarela, sin que esto aumente el canon.'],
  ['', 'EL ARRENDATARIO solo entregará copia de las llaves a personas de su confianza.'],
  ['', 'Terminada la mudanza, EL ARRENDATARIO avisará inmediatamente a la administración.'],
  ['', 'Al terminar el contrato, EL ARRENDATARIO entregará el inmueble pintado.'],
  ['', 'EL ARRENDATARIO impedirá el ingreso de personas ajenas a las zonas comunes y avisará al ARRENDADOR.'],
  ['', 'EL ARRENDATARIO no podrá cambiar las guardas sin autorización del ARRENDADOR.'],
  ['', 'EL ARRENDATARIO podrá guardar su bicicleta en el depósito del edificio.'],
  ['', 'EL ARRENDATARIO usará el parqueadero asignado y no podrá estacionar en zonas comunes.'],
  ['', 'EL ARRENDATARIO sacará la basura los lunes, miércoles y viernes después de las 6 p. m.'],
  ['', 'EL ARRENDATARIO no hará ruido después de las 10 p. m. y respetará el reglamento.'],
  ['', 'EL ARRENDATARIO pintará el inmueble de color blanco al entregarlo.'],
  ['', 'EL ARRENDATARIO asumirá las reparaciones locativas de acuerdo con la ley.'],
  ['', 'EL ARRENDATARIO pagará las tarifas de los servicios públicos que consuma.'],
  ['', 'La tarifa del parqueadero de visitantes la fija la administración.'],
  ['', 'EL ARRENDATARIO pagará la prima del seguro de hogar que contrate.'],
  ['', 'Los servicios públicos quedarán cubiertos por EL ARRENDATARIO.'],
  ['', 'Durante la mudanza los muebles quedarán cubiertos con plástico para evitar daños.'],
  ['', 'EL ARRENDADOR efectuará las reparaciones necesarias dentro de los diez días siguientes al aviso.'],
  ['', 'EL ARRENDATARIO informará por escrito al ARRENDADOR las reparaciones necesarias.'],
  ['', 'EL ARRENDATARIO permitirá que EL ARRENDADOR realice las reparaciones necesarias.'],
  ['', 'EL ARRENDATARIO no podrá cambiar el color de las paredes del apartamento sin autorización escrita del ARRENDADOR.'],
  ['', 'EL ARRENDATARIO usará el parqueadero N.º 12 y el cuarto útil 1.ª planta.'],
  ['', 'EL ARRENDATARIO pagará la cuota de administración, que hoy es de $350.000 (trescientos cincuenta mil pesos).'],
  ['', 'EL ARRENDATARIO mantendrá la temperatura del calentador por debajo de 60 °C.'],
  ['', 'EL ARRENDATARIO dejará el inmueble libre de basura; la empresa de aseo recoge los martes y jueves.'],
  ['', 'El área del inmueble es de 60 m² aproximadamente y EL ARRENDATARIO la recibe a satisfacción.'],
  ['', 'EL ARRENDATARIO usará la zona BBQ del conjunto conforme al reglamento.'],
];
